# Generated by Django 2.2.16 on 2020-09-24 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('user_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='用户id,不对外展示')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='最近一次登录时间')),
                ('login_time_last', models.DateTimeField(auto_now_add=True, verbose_name='上次登录时间')),
                ('online_avg', models.CharField(max_length=256, verbose_name='平均在线时长')),
                ('online_time', models.CharField(max_length=256, verbose_name='共计在线时长')),
            ],
        ),
        migrations.CreateModel(
            name='Passwd',
            fields=[
                ('user_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='用户id,不对外展示')),
                ('passwd', models.CharField(max_length=128, verbose_name='密码')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='修改日期')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='token_id')),
                ('user_id', models.CharField(max_length=32, verbose_name='用户id,不对外展示')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='用户id,不对外展示')),
                ('user_name', models.CharField(max_length=128, verbose_name='用户名')),
                ('nick_name', models.CharField(max_length=128, verbose_name='昵称')),
                ('user_number', models.CharField(max_length=128, verbose_name='数字账号')),
                ('sign_time', models.DateTimeField(auto_now_add=True, verbose_name='注册日期')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cheat.User')),
                ('mail', models.CharField(max_length=128, verbose_name='邮箱')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
            ],
            bases=('cheat.user',),
        ),
    ]
