# Generated by Django 2.2.16 on 2020-09-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='friends',
            fields=[
                ('user_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='用户id,不对外展示')),
                ('friend_id', models.CharField(max_length=4096, verbose_name='好友id及昵称')),
                ('meet_date', models.DateTimeField(auto_now_add=True, verbose_name='加好友日期')),
                ('black_list', models.CharField(max_length=32, verbose_name='黑名单的用户id')),
                ('special_care', models.CharField(max_length=32, verbose_name='特别关心好友')),
            ],
        ),
        migrations.CreateModel(
            name='group',
            fields=[
                ('group_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='用户id,不对外展示')),
                ('group_name', models.CharField(max_length=32, verbose_name='群名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('group_member', models.CharField(max_length=4096, verbose_name='群成员')),
                ('join_method', models.CharField(max_length=64, verbose_name='进群方式')),
                ('admin_id', models.CharField(max_length=32, verbose_name='群主id')),
                ('is_everyone_invite', models.BooleanField(verbose_name='是否允许成员邀请')),
                ('black_list', models.CharField(max_length=32, verbose_name='黑名单的用户id')),
            ],
        ),
    ]
